### ISSUE TITLE
DST-1 Аналіз Даних (Exploratory Data Analysis)

### ISSUE THREAD

**Issue by AndriiLi** [AndriiLi/project1_group2#1]
**Ціль:**

1. Вивчити розподіли.
2. Визначити основні характеристики даних: розмір датасету, типи даних.
3. Виявити відсутні значення.
4. Провести аналіз кореляцій та залежностей між змінними.
5. Виявити аномалії (Outliers): знайти дані, які відрізняються від інших.
6. Зробити висновок за результатами проведеного аналізу даних.

**Результат:**

1. Датасет проаналізований та готовий для подальшої попередньої обробки даних.
2. Зроблено висновок за результатами проведеного аналізу даних.
3. Зроблені висновки та збережені у файлі.
4. Складено файл за основними характеристиками датасету.

**Comment by HannaMalygina** [comment]
ToDo: create a txt file with a summary:
which data was deleted
how the data was normalised
which data is categorical

**Comment by vkbyba** [comment]
Виклав файл.

По суті, тільки підмінив 0 пусті вельюзи

**Comment by vkbyba** [comment]
Є два датасети;
В одному remaining_contract = Nan конвертували в 0 - https://github.com/AndriiLi/project1_group2/blob/main/data/updated_internet_service_churn_byba-1.csv
в іншому remaining_contract = Nan конвертували в -1 -
https://github.com/AndriiLi/project1_group2/blob/main/data/updated_internet_service_churn_byba.csv
