### ISSUE TITLE
DST-2 Попередня Обробка Даних

### ISSUE THREAD

**Issue by AndriiLi** [AndriiLi/project1_group2#2]
**Ціль:**

1. Виконати обробку відсутніх значень: заповнення або видалення.
2. Закодувати категоріальні змінні: One-Hot Encoding або Label Encoding.
3. Провести нормалізацію ознак: стандартизація.
4. Виконати візуалізацію даних за допомогою графічних представлень для кращого розуміння даних та їх структури.

**Результат:**

1. Проведена попередня обробка даних.
2. Побудований файл з обробленими даними.
3. Написані функції для візуалізації даних.
4. Зроблені висновки та збережені у файлі.

**Comment by HannaMalygina** [comment]
Дані попередньо підготовлено до наступної задачі. Думаю, можна починати будувати модель. 
data/cleaned_norm_data.csv

Як зрозуміємо детальніше значення колонок, тоді дані перепідготую знову.

**Comment by vkbyba** [comment]
Є два датасети;
В одному remaining_contract = Nan конвертували в 0 - https://github.com/AndriiLi/project1_group2/blob/main/data/updated_internet_service_churn_byba-1.csv
в іншому remaining_contract = Nan конвертували в -1 -
https://github.com/AndriiLi/project1_group2/blob/main/data/updated_internet_service_churn_byba.csv

**Comment by HannaMalygina** [comment]
очистка даних:
download_avg, upload_avg:відсутні значення замінені на 0
remaining_contract: відсутні значення замінені двома способами:  0 і -1. Для обидвох треба потренувати модель і глянути, з якими крище виходить. (див попередній коментар Володимира)

Не важливими змінними виявилися наступні (базуючись на кореляціній матриці):
bill_avg, service_failure_count. 
З іншого боку bill_avg має велику варіативність.

Пропоную викинути поки що з моделі лише service_failure_count.
А також id користувача.


![Image](https://github.com/user-attachments/assets/c41bd120-1b8e-4af5-9dda-9beed53cfae0)
