### ISSUE TITLE
DST-0 Обрати назву команди та її логотип

### ISSUE THREAD

**Issue by AndriiLi** [AndriiLi/project1_group2#7]
**Ціль** 

- Обрати назву команди та її логотип
- Створити тред у Slack або загальний дзвінок з командою для узгодження цих цілей.

**Результат:**

- Назва та логотип обрані

**Comment by HannaMalygina** [comment]
Пропозиції назв команди:
DataPioneers
ByteCraft

![Image](https://github.com/user-attachments/assets/66880201-f6a0-4e5b-ba8b-ad18e3baa21a)

**Comment by HannaMalygina** [comment]
Name: Augures
Logo:

![Image](https://github.com/user-attachments/assets/b909b8be-7b41-4afd-85d0-2bed7d67f700)
